# Generated by Django 3.2.9 on 2021-12-04 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bron',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('bron', models.TextField(db_column='Bron', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Czynniki',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('czynnik', models.CharField(max_length=50)),
                ('parametr', models.CharField(max_length=50)),
                ('temperatura', models.IntegerField()),
                ('wypelnienie', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rodzaj', models.TextField(blank=True, db_column='Rodzaj', null=True)),
                ('id_czynnik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.czynniki')),
            ],
        ),
        migrations.CreateModel(
            name='Pocisk',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nazwa', models.TextField(db_column='Nazwa', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podloza',
            fields=[
                ('id_podloze', models.AutoField(primary_key=True, serialize=False)),
                ('podloze', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProbaStrzelnicza',
            fields=[
                ('id_proby', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('warunki_atmosferyczne', models.TextField()),
                ('predkosc_wiatru', models.IntegerField()),
                ('czynnik', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.czynniki')),
                ('id_bron', models.ForeignKey(db_column='id_bron', on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.bron')),
                ('id_pocisk', models.ForeignKey(db_column='id_pocisk', on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.pocisk')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.material')),
                ('podloze', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.podloza')),
            ],
        ),
        migrations.CreateModel(
            name='Rykoszet',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('material', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pliki',
            fields=[
                ('id_proby', models.OneToOneField(db_column='id_proby', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='proba_strzelnicza.probastrzelnicza')),
                ('kamera_zwykla', models.CharField(max_length=50)),
                ('kamera_szybka', models.CharField(max_length=50)),
                ('kamera_ir', models.CharField(max_length=50)),
                ('kamera_ir_szybka', models.CharField(max_length=50)),
                ('zdjecie', models.CharField(max_length=50)),
                ('proba_strzelnicza_id_proby', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='probastrzelnicza',
            name='rykoszet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.rykoszet'),
        ),
    ]
