# Generated by Django 3.2.9 on 2021-12-06 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proba_strzelnicza', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pliki',
            old_name='zdjecie',
            new_name='link',
        ),
    ]
