# Generated by Django 3.2.9 on 2021-12-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proba_strzelnicza', '0002_rename_zdjecie_pliki_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pliki',
            old_name='kamera_ir_szybka',
            new_name='zdjecie',
        ),
    ]
