# Generated by Django 3.2.9 on 2021-12-06 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proba_strzelnicza', '0006_auto_20211206_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pliki',
            name='kamera_ir',
        ),
        migrations.RemoveField(
            model_name='pliki',
            name='kamera_szybka',
        ),
    ]
