# Generated by Django 3.2.9 on 2021-12-06 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba_strzelnicza', '0007_auto_20211206_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='probastrzelnicza',
            name='kamera_ir',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
