# Generated by Django 3.2.9 on 2021-12-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba_strzelnicza', '0009_remove_probastrzelnicza_czynnik'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='id_czynnik',
        ),
        migrations.AddField(
            model_name='czynniki',
            name='proby',
            field=models.ManyToManyField(blank=True, related_name='czynniki', to='proba_strzelnicza.ProbaStrzelnicza'),
        ),
    ]
