# Generated by Django 3.2.9 on 2021-12-08 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proba_strzelnicza', '0012_material_id_czynnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='id_czynnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.czynniki'),
        ),
        migrations.AlterField(
            model_name='probastrzelnicza',
            name='czynnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.czynniki'),
        ),
    ]
