# Generated by Django 3.2.9 on 2021-12-08 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba_strzelnicza', '0013_auto_20211208_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='probastrzelnicza',
            name='link_kaliber',
            field=models.CharField(default=1, max_length=80),
        ),
    ]
