# Generated by Django 3.2.9 on 2021-12-09 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proba_strzelnicza', '0016_alter_probastrzelnicza_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='probastrzelnicza',
            name='wypelnienie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ilosc', to='proba_strzelnicza.czynniki'),
        ),
    ]
