# Generated by Django 3.2.9 on 2021-12-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba_strzelnicza', '0017_probastrzelnicza_wypelnienie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probastrzelnicza',
            name='parametr',
        ),
        migrations.RemoveField(
            model_name='probastrzelnicza',
            name='wypelnienie',
        ),
        migrations.AlterField(
            model_name='probastrzelnicza',
            name='temperatura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
