# Generated by Django 3.2.9 on 2021-12-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba_strzelnicza', '0018_auto_20211209_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pliki',
            name='zdjecie',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
