# Generated by Django 3.2.9 on 2022-01-02 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proba_strzelnicza', '0020_auto_20220102_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probastrzelnicza',
            name='kamera_ir',
        ),
        migrations.AddField(
            model_name='pliki',
            name='kamera_ir',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
